// A representative target muscle for each exercise, not an exhaustive anatomy guide.
export const exerciseCatalog = [
  { name: 'Push-ups', muscle: 'Chest', equipment: 'Bodyweight', parts: ['chest'], side: 'front' },
  { name: 'Squats', muscle: 'Quadriceps', equipment: 'Bodyweight', parts: ['quadriceps'], side: 'front' },
  { name: 'Lunges', muscle: 'Quadriceps', equipment: 'Bodyweight', parts: ['quadriceps'], side: 'front' },
  { name: 'Bench press', muscle: 'Chest', equipment: 'Barbell', parts: ['chest'], side: 'front' },
  { name: 'Dumbbell row', muscle: 'Back', equipment: 'Dumbbell', parts: ['upper-back'], side: 'back' },
  { name: 'Bicep curls', muscle: 'Biceps', equipment: 'Dumbbell', parts: ['biceps'], side: 'front' },
  { name: 'Deadlift', muscle: 'Hamstrings / glutes', equipment: 'Barbell', parts: ['hamstring', 'gluteal'], side: 'back' },
  { name: 'Shoulder press', muscle: 'Shoulders', equipment: 'Dumbbell', parts: ['deltoids'], side: 'front' },
  { name: 'Pull-ups', muscle: 'Back', equipment: 'Pull-up bar', parts: ['upper-back'], side: 'back' },
  { name: 'Sit-ups', muscle: 'Abdominals', equipment: 'Bodyweight', parts: ['abs'], side: 'front' },
  { name: 'Calf raises', muscle: 'Calves', equipment: 'Bodyweight', parts: ['calves'], side: 'back' },
  { name: 'Tricep extensions', muscle: 'Triceps', equipment: 'Dumbbell', parts: ['triceps'], side: 'back' },
  // Additional rep-based exercises. Timed holds need a separate duration input.
  {"name": "Incline bench press", "muscle": "Chest", "equipment": "Barbell", "parts": ["chest"], "side": "front"},
  {"name": "Dumbbell bench press", "muscle": "Chest", "equipment": "Dumbbell", "parts": ["chest"], "side": "front"},
  {"name": "Incline dumbbell press", "muscle": "Chest", "equipment": "Dumbbell", "parts": ["chest"], "side": "front"},
  {"name": "Dumbbell fly", "muscle": "Chest", "equipment": "Dumbbell", "parts": ["chest"], "side": "front"},
  {"name": "Cable fly", "muscle": "Chest", "equipment": "Cable", "parts": ["chest"], "side": "front"},
  {"name": "Chest press", "muscle": "Chest", "equipment": "Machine", "parts": ["chest"], "side": "front"},
  {"name": "Lat pulldown", "muscle": "Back", "equipment": "Cable", "parts": ["upper-back"], "side": "back"},
  {"name": "Seated cable row", "muscle": "Back", "equipment": "Cable", "parts": ["upper-back"], "side": "back"},
  {"name": "Barbell row", "muscle": "Back", "equipment": "Barbell", "parts": ["upper-back"], "side": "back"},
  {"name": "Chin-ups", "muscle": "Back", "equipment": "Pull-up bar", "parts": ["upper-back"], "side": "back"},
  {"name": "Chest-supported row", "muscle": "Back", "equipment": "Dumbbell", "parts": ["upper-back"], "side": "back"},
  {"name": "Lateral raises", "muscle": "Shoulders", "equipment": "Dumbbell", "parts": ["deltoids"], "side": "front"},
  {"name": "Front raises", "muscle": "Shoulders", "equipment": "Dumbbell", "parts": ["deltoids"], "side": "front"},
  {"name": "Arnold press", "muscle": "Shoulders", "equipment": "Dumbbell", "parts": ["deltoids"], "side": "front"},
  {"name": "Overhead press", "muscle": "Shoulders", "equipment": "Barbell", "parts": ["deltoids"], "side": "front"},
  {"name": "Hammer curls", "muscle": "Biceps", "equipment": "Dumbbell", "parts": ["biceps"], "side": "front"},
  {"name": "Barbell curls", "muscle": "Biceps", "equipment": "Barbell", "parts": ["biceps"], "side": "front"},
  {"name": "Cable curls", "muscle": "Biceps", "equipment": "Cable", "parts": ["biceps"], "side": "front"},
  {"name": "Tricep pushdown", "muscle": "Triceps", "equipment": "Cable", "parts": ["triceps"], "side": "back"},
  {"name": "Skull crushers", "muscle": "Triceps", "equipment": "Barbell", "parts": ["triceps"], "side": "back"},
  {"name": "Close-grip bench press", "muscle": "Triceps", "equipment": "Barbell", "parts": ["triceps"], "side": "back"},
  {"name": "Barbell squat", "muscle": "Quadriceps", "equipment": "Barbell", "parts": ["quadriceps"], "side": "front"},
  {"name": "Goblet squat", "muscle": "Quadriceps", "equipment": "Dumbbell", "parts": ["quadriceps"], "side": "front"},
  {"name": "Leg press", "muscle": "Quadriceps", "equipment": "Machine", "parts": ["quadriceps"], "side": "front"},
  {"name": "Leg extension", "muscle": "Quadriceps", "equipment": "Machine", "parts": ["quadriceps"], "side": "front"},
  {"name": "Bulgarian split squat", "muscle": "Quadriceps", "equipment": "Dumbbell", "parts": ["quadriceps"], "side": "front"},
  {"name": "Romanian deadlift", "muscle": "Hamstrings / glutes", "equipment": "Barbell", "parts": ["hamstring", "gluteal"], "side": "back"},
  {"name": "Leg curl", "muscle": "Hamstrings", "equipment": "Machine", "parts": ["hamstring"], "side": "back"},
  {"name": "Hip thrust", "muscle": "Glutes", "equipment": "Barbell", "parts": ["gluteal"], "side": "back"},
  {"name": "Glute bridge", "muscle": "Glutes", "equipment": "Bodyweight", "parts": ["gluteal"], "side": "back"},
  {"name": "Seated calf raise", "muscle": "Calves", "equipment": "Machine", "parts": ["calves"], "side": "back"},
  {"name": "Crunches", "muscle": "Abdominals", "equipment": "Bodyweight", "parts": ["abs"], "side": "front"},
  {"name": "Reverse crunches", "muscle": "Abdominals", "equipment": "Bodyweight", "parts": ["abs"], "side": "front"},
  {"name": "Hanging knee raises", "muscle": "Abdominals", "equipment": "Pull-up bar", "parts": ["abs"], "side": "front"},
  {"name": "Cable crunch", "muscle": "Abdominals", "equipment": "Cable", "parts": ["abs"], "side": "front"},
  {"name": "Bicycle crunches", "muscle": "Obliques", "equipment": "Bodyweight", "parts": ["obliques"], "side": "front"},
];
